# Auto-generated by the "new-dockerfile" CLI tool
# Please report any issues to: https://github.com/flexstack/new-dockerfile/issues
ARG VERSION=2
FROM joseluisq/static-web-server:${VERSION}-debian
RUN apt-get update && apt-get install -y --no-install-recommends wget && apt-get clean && rm -f /var/lib/apt/lists/*_*
COPY . .

ARG PORT=8080
EXPOSE ${PORT}
ENV PORT=${PORT}
ENV SERVER_PORT=${PORT}
ARG SERVER_ROOT=.
ENV SERVER_ROOT=${SERVER_ROOT}
ENV SERVER_IGNORE_HIDDEN_FILES=true
ENV SERVER_SECURITY_HEADERS=true
ENV SERVER_COMPRESSION=false
ENV SERVER_LOG_LEVEL=info
